
title: גדי רואה DS9
email: gadial@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  יומן צפיה ב"חלל עמוק 9"
baseurl: "/ds9" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: GadiWatchesDS9
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  
collections:
  reviews:
    output: true

exclude:
  - docs
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
