
title: גדי רואה DS9
email: gadial@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  יומן צפיה ב"חלל עמוק 9"
baseurl: "/ds9" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: GadiWatchesDS9
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
environment: production
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/general/DS9.jpg
      description: "גדי רואה DS9 - יומן צפיה בסדרה Deep Space 9"

collections:
  reviews:
    output: true

# Trackers
google_analytics: "UA-3924539-3"
statcounter:
  id: 12182652
  security: 915773f6
  invisible: 1

exclude:
  - docs
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
